
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.VBox vbox8;
	private global::Gtk.Label CalendarioAnual;
	private global::Gtk.Calendar calendar1;
	private global::Gtk.Label TituloFormulario;
	private global::Gtk.HBox hbox8;
	private global::Gtk.Label label1;
	private global::Gtk.Entry entryNombre;
	private global::Gtk.HBox hbox9;
	private global::Gtk.Label label2;
	private global::Gtk.Entry entryApellidos;
	private global::Gtk.VBox vbox11;
	private global::Gtk.HBox hbox10;
	private global::Gtk.Label label3;
	private global::Gtk.Entry entryCurso;
	private global::Gtk.HBox hbox11;
	private global::Gtk.Label label4;
	private global::Gtk.Entry entryNota;
	private global::Gtk.VBox vbox12;
	private global::Gtk.HBox hbox12;
	private global::Gtk.Label label5;
	private global::Gtk.Entry entryModulo;
	private global::Gtk.VBox vbox13;
	private global::Gtk.Button buttonResumen;
	private global::Gtk.Label labelResumen;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox8 = new global::Gtk.VBox ();
		this.vbox8.Name = "vbox8";
		this.vbox8.Spacing = 6;
		this.vbox8.BorderWidth = ((uint)(6));
		// Container child vbox8.Gtk.Box+BoxChild
		this.CalendarioAnual = new global::Gtk.Label ();
		this.CalendarioAnual.Name = "CalendarioAnual";
		this.CalendarioAnual.LabelProp = global::Mono.Unix.Catalog.GetString ("CALENDARIO ANUAL CURSO");
		this.vbox8.Add (this.CalendarioAnual);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.CalendarioAnual]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.calendar1 = new global::Gtk.Calendar ();
		this.calendar1.CanFocus = true;
		this.calendar1.Name = "calendar1";
		this.calendar1.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
		this.vbox8.Add (this.calendar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.calendar1]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.TituloFormulario = new global::Gtk.Label ();
		this.TituloFormulario.Name = "TituloFormulario";
		this.TituloFormulario.LabelProp = global::Mono.Unix.Catalog.GetString ("FORMULARIO RESUMEN CURSO");
		this.vbox8.Add (this.TituloFormulario);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.TituloFormulario]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox ();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.Xalign = 1F;
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Nombre");
		this.hbox8.Add (this.label1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.label1]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.entryNombre = new global::Gtk.Entry ();
		this.entryNombre.CanFocus = true;
		this.entryNombre.Name = "entryNombre";
		this.entryNombre.IsEditable = true;
		this.entryNombre.InvisibleChar = '•';
		this.hbox8.Add (this.entryNombre);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.entryNombre]));
		w5.Position = 1;
		this.vbox8.Add (this.hbox8);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox8]));
		w6.Position = 3;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox ();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.Xalign = 1F;
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Apellidos");
		this.hbox9.Add (this.label2);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.label2]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.entryApellidos = new global::Gtk.Entry ();
		this.entryApellidos.CanFocus = true;
		this.entryApellidos.Name = "entryApellidos";
		this.entryApellidos.IsEditable = true;
		this.entryApellidos.InvisibleChar = '•';
		this.hbox9.Add (this.entryApellidos);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.entryApellidos]));
		w8.Position = 1;
		this.vbox8.Add (this.hbox9);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox9]));
		w9.Position = 4;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.vbox11 = new global::Gtk.VBox ();
		this.vbox11.Name = "vbox11";
		this.vbox11.Spacing = 6;
		// Container child vbox11.Gtk.Box+BoxChild
		this.hbox10 = new global::Gtk.HBox ();
		this.hbox10.Name = "hbox10";
		this.hbox10.Spacing = 6;
		// Container child hbox10.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.Xalign = 1F;
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Curso");
		this.hbox10.Add (this.label3);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.label3]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.entryCurso = new global::Gtk.Entry ();
		this.entryCurso.CanFocus = true;
		this.entryCurso.Name = "entryCurso";
		this.entryCurso.IsEditable = true;
		this.entryCurso.InvisibleChar = '•';
		this.hbox10.Add (this.entryCurso);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.entryCurso]));
		w11.Position = 1;
		this.vbox11.Add (this.hbox10);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.hbox10]));
		w12.Position = 0;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox11.Gtk.Box+BoxChild
		this.hbox11 = new global::Gtk.HBox ();
		this.hbox11.Name = "hbox11";
		this.hbox11.Spacing = 6;
		// Container child hbox11.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.Xalign = 1F;
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Nota");
		this.hbox11.Add (this.label4);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.label4]));
		w13.Position = 0;
		w13.Expand = false;
		w13.Fill = false;
		// Container child hbox11.Gtk.Box+BoxChild
		this.entryNota = new global::Gtk.Entry ();
		this.entryNota.CanFocus = true;
		this.entryNota.Name = "entryNota";
		this.entryNota.IsEditable = true;
		this.entryNota.InvisibleChar = '•';
		this.hbox11.Add (this.entryNota);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.entryNota]));
		w14.Position = 1;
		this.vbox11.Add (this.hbox11);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.hbox11]));
		w15.Position = 1;
		w15.Expand = false;
		w15.Fill = false;
		// Container child vbox11.Gtk.Box+BoxChild
		this.vbox12 = new global::Gtk.VBox ();
		this.vbox12.Name = "vbox12";
		this.vbox12.Spacing = 6;
		// Container child vbox12.Gtk.Box+BoxChild
		this.hbox12 = new global::Gtk.HBox ();
		this.hbox12.Name = "hbox12";
		this.hbox12.Spacing = 6;
		// Container child hbox12.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.Xalign = 1F;
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Modulo");
		this.hbox12.Add (this.label5);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.label5]));
		w16.Position = 0;
		w16.Expand = false;
		w16.Fill = false;
		// Container child hbox12.Gtk.Box+BoxChild
		this.entryModulo = new global::Gtk.Entry ();
		this.entryModulo.CanFocus = true;
		this.entryModulo.Name = "entryModulo";
		this.entryModulo.IsEditable = true;
		this.entryModulo.InvisibleChar = '•';
		this.hbox12.Add (this.entryModulo);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.entryModulo]));
		w17.Position = 1;
		this.vbox12.Add (this.hbox12);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.hbox12]));
		w18.Position = 0;
		w18.Expand = false;
		w18.Fill = false;
		// Container child vbox12.Gtk.Box+BoxChild
		this.vbox13 = new global::Gtk.VBox ();
		this.vbox13.Name = "vbox13";
		this.vbox13.Spacing = 6;
		// Container child vbox13.Gtk.Box+BoxChild
		this.buttonResumen = new global::Gtk.Button ();
		this.buttonResumen.CanFocus = true;
		this.buttonResumen.Name = "buttonResumen";
		this.buttonResumen.UseStock = true;
		this.buttonResumen.UseUnderline = true;
		this.buttonResumen.Label = "RESUMEN CURSO";
		this.vbox13.Add (this.buttonResumen);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.buttonResumen]));
		w19.Position = 0;
		w19.Expand = false;
		w19.Fill = false;
		// Container child vbox13.Gtk.Box+BoxChild
		this.labelResumen = new global::Gtk.Label ();
		this.labelResumen.Name = "labelResumen";
		this.labelResumen.LabelProp = global::Mono.Unix.Catalog.GetString ("Pulsa RESUMEN CURSO!!!!");
		this.vbox13.Add (this.labelResumen);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.labelResumen]));
		w20.Position = 1;
		w20.Expand = false;
		w20.Fill = false;
		this.vbox12.Add (this.vbox13);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.vbox13]));
		w21.Position = 1;
		w21.Expand = false;
		w21.Fill = false;
		this.vbox11.Add (this.vbox12);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.vbox12]));
		w22.Position = 2;
		w22.Expand = false;
		w22.Fill = false;
		this.vbox8.Add (this.vbox11);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.vbox11]));
		w23.Position = 5;
		w23.Expand = false;
		w23.Fill = false;
		this.Add (this.vbox8);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 621;
		this.DefaultHeight = 476;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.buttonResumen.Clicked += new global::System.EventHandler (this.OnButtonClicked);
	}
}
